from enum import Enum, auto

class State(Enum):
    IDLE         = auto()
    IDLE_2       = auto()
    WALK         = auto()
    RUN          = auto()
    JUMP         = auto()
    ROLL         = auto()
    HANG         = auto()
    PULL_UP      = auto()
    CLIMB        = auto()
    ATTACK_1     = auto()
    ATTACK_2     = auto()
    ATTACK_3     = auto()
    RUN_ATTACK   = auto()
    JUMP_ATTACK  = auto()
    POWER_ATK_1  = auto()
    POWER_ATK_2  = auto()
    SHIELD_STRIKE = auto()
    BLOCK        = auto()
    DEFEND       = auto()
    HURT         = auto()
    DEAD         = auto()
    ELIXIR       = auto()
    INVOCATION   = auto()
    PICK_UP      = auto()